

# Site settings
title: BioImage Analysis
email: your-email@domain.com
description: "Cedric Espenel bioimage analysis at Stanford"


# Team names, titles and social links
people:
- name: Cedric Espenel
  pic: 1
  position: Imaging Specialist


# Postal address (add as many lines as necessary)
address:
  - line: 443 Via Ortega
  - line: Stanford, CA 94305

# Build settings
markdown: kramdown
permalink: pretty

collections:
  guides:
    output: true
